import Route from '@ember/routing/route';
import { service } from '@ember/service';

export default class LeagueRoute extends Route {
  @service store;

  model(params) {
    return this.store.findRecord('league', params.league_id);
  }

  async breadcrumbParents(model) {
    const org = this.modelFor('orgs.org');
    const season = await model.season;
    const activityType = await season.activityType;
    return [
      { route: 'orgs.org.activity-types', model: [ org ] },
      { route: 'orgs.org.activity-types.activity-type', model: [ org, activityType ] },
      { route: 'orgs.org.seasons.season', model: [ org, season ] },
    ]
  }

  breadcrumb(model) {
    return { title: model.name || model.autoGeneratedName };
  }
}
