import Model, { attr, belongsTo, hasMany } from '@ember-data/model';

export default class LeagueModel extends Model {
  @attr('string') name;
  @attr('string') gender;
  @attr('number') minGrade;
  @attr('number') maxGrade;
  @attr('number') minAge;
  @attr('number') maxAge;
  @attr('string') ageCutoffDate;
  @attr('number') capacity;
  @attr('boolean') full;
  @attr('string') autoGeneratedName;

  @belongsTo('season', { async: true, inverse: 'leagues' }) season;
  @hasMany('team', { async: true, inverse: 'league' }) teams;
  @hasMany('registration', { async: true, inverse: 'league' }) registrations;
}
